name: CI

on: [push]

jobs:
 sast_scan:
   name: run the source code analysis
   runs-on: ubuntu-latest

   steps:
    - name: checking the code
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Snyk
  # You may pin to the exact commit or the version.
  # uses: snyk/actions@b98d498629f1c368650224d6d212bf7dfa89e4bf
      uses: snyk/actions@0.4.0
      with:
    # Which Snyk command to run, defaults to test
      command: snyk code test
    # Additional arguments to pass to Snyk
      args: # optional
    # Output a snyk.json file with results if running the test command
      json: # optional
          
     
